import type { Metadata } from "next";
import { Lato, Quicksand } from "next/font/google";
import Footer from "../layout/Footer";
import "./globals.css";
import Header from "@/layout/Header";

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["400", "700"],
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Bicycle Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${quicksand.variable} antialiased container overflow-x-hidden`}
      >
        <div className="container mx-auto max-w-[1280px] px-4 ">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
